import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {QueryClient,QueryClientProvider,useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import './style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
async function api(path:string,init:RequestInit={}){const token=localStorage.getItem('token'); const r=await fetch(API+path,{...init,headers:{...(init.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(token?{Authorization:`Bearer ${token}`}:{})}}); const d=await r.json().catch(()=>({})); if(!r.ok) throw new Error(typeof d.detail==='string'?d.detail:d.detail?.message||'Request failed'); return d;}
function Login({onLogin}:{onLogin:()=>void}){const [u,setU]=useState('admin'),[p,setP]=useState('admin123'),[err,setErr]=useState('');return <main className="center"><form className="card login" onSubmit={async e=>{e.preventDefault();try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({username:u,password:p})});localStorage.setItem('token',d.token);localStorage.setItem('role',d.role);onLogin()}catch(e:any){setErr(e.message)}}}><h1>Peblo CMS</h1><p>Internal content publishing</p><input value={u} onChange={e=>setU(e.target.value)} placeholder="Username"/><input value={p} onChange={e=>setP(e.target.value)} type="password" placeholder="Password"/><button>Sign in</button>{err&&<div className="error">{err}</div>}<small>Demo: admin/admin123 · editor/editor123</small></form></main>}
function App(){const [authed,setAuthed]=useState(!!localStorage.getItem('token')); const [tab,setTab]=useState('shows'); if(!authed)return <Login onLogin={()=>setAuthed(true)}/>; return <div><header><strong>Peblo CMS</strong><nav><button onClick={()=>setTab('shows')}>Shows</button><button onClick={()=>setTab('publish')}>Publish</button></nav><span>{localStorage.getItem('role')}</span><button onClick={()=>{localStorage.clear();setAuthed(false)}}>Sign out</button></header>{tab==='shows'?<Shows/>:<Publish/>}</div>}
function Shows(){const qc=useQueryClient(); const [q,setQ]=useState(''); const shows=useQuery({queryKey:['shows',q],queryFn:()=>api('/admin/shows?q='+encodeURIComponent(q))}); const [selected,setSelected]=useState<any>(null); return <main className="page"><div className="toolbar"><h2>Content</h2><input placeholder="Search shows" value={q} onChange={e=>setQ(e.target.value)}/></div>{shows.isLoading?<p>Loading…</p>:shows.isError?<div className="error">{(shows.error as Error).message}</div>:<div className="grid">{shows.data.map((s:any)=><div className="card" key={s.id} onClick={()=>setSelected(s)}><h3>{s.title}</h3><p>{s.section||'No section'}</p><div className="tags">{s.categories.map((c:string)=><span key={c}>{c}</span>)}</div><small>{s.status}</small></div>)}</div>}{selected&&<EpisodePanel show={selected} close={()=>setSelected(null)} refresh={()=>qc.invalidateQueries({queryKey:['shows']})}/>}</main>}
function EpisodePanel({show,close,refresh}:{show:any,close:()=>void,refresh:()=>void}){const eps=useQuery({queryKey:['episodes',show.id],queryFn:()=>api('/admin/episodes?show_id='+show.id)}); const [kind,setKind]=useState('poster'); const [ep,setEp]=useState(''); const upload=useMutation({mutationFn:async(file:File)=>{const f=new FormData();f.append('file',file);return api(`/admin/episodes/${ep}/artwork?kind=${kind}`,{method:'POST',body:f})}});return <div className="modal"><div className="card modalbox"><button className="close" onClick={close}>×</button><h2>{show.title}</h2><p>{show.synopsis}</p>{eps.isLoading?<p>Loading episodes…</p>:<><select value={ep} onChange={e=>setEp(e.target.value)}><option value="">Select episode</option>{eps.data.map((e:any)=><option key={e.episode_id} value={e.episode_id}>{e.episode_id} — {e.title}</option>)}</select><div className="uploadrow">{['poster','banner','thumbnail'].map(k=><label key={k}><b>{k}</b><small>{k==='poster'?'600×900 · 2:3':k==='banner'?'1280×720 · 16:9':'640×360 · 16:9'} · max 200 KB</small><input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f&&ep){setKind(k);upload.mutate(f)}}}/></label>)}</div>{upload.isError&&<div className="error">{(upload.error as Error).message}</div>}{upload.isSuccess&&<div className="success">Artwork uploaded successfully.</div>}</>}</div></div>}
function Publish(){const qc=useQueryClient(); const report=useQuery({queryKey:['report'],queryFn:()=>api('/admin/validation-report')}); const runs=useQuery({queryKey:['runs'],queryFn:()=>api('/admin/publish-runs')}); const pub=useMutation({mutationFn:()=>api('/admin/catalog/publish',{method:'POST'}),onSuccess:()=>{qc.invalidateQueries({queryKey:['report']});qc.invalidateQueries({queryKey:['runs']})}});return <main className="page"><h2>Publish catalogue</h2>{report.isLoading?<p>Checking content…</p>:report.data.blocking?<div className="card"><h3>Publishing blocked</h3><p>{report.data.count} issue(s) need attention.</p>{Object.entries(report.data.groups).map(([g,items]:any)=><section key={g}><h4>{g}</h4>{items.map((i:any)=><div className="issue" key={i.entity+i.field}><b>{i.entity}</b><div>{i.message}</div><small>Fix: {i.action}</small></div>)}</section>)}</div>:<div className="card"><h3>Ready to publish</h3><button disabled={pub.isPending} onClick={()=>pub.mutate()}>{pub.isPending?'Publishing…':'Publish catalogue'}</button></div>}{pub.isError&&<div className="error">{(pub.error as Error).message}</div>}<div className="card"><h3>Run history</h3>{runs.data?.map((r:any)=><div className="run" key={r.id}><b>#{r.id} {r.status}</b><span>{r.triggered_by}</span><span>{r.show_count} shows · {r.episode_count} episodes</span></div>)}</div></main>}
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={new QueryClient()}><App/></QueryClientProvider>);
