import {createRoot} from 'react-dom/client';import {QueryClient,QueryClientProvider,useQuery} from '@tanstack/react-query';import {BrowserRouter,useNavigate,useParams} from 'react-router-dom';import {Routes,Route,Link} from 'react-router-dom';import './style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
async function get(path:string){const r=await fetch(API+path);if(!r.ok)throw new Error((await r.text())||'Unable to load catalogue');return r.json()}
const img=(u:string)=>u?.startsWith('http')?u:API+u;
function Layout({children}:{children:any}){return <><header><Link to="/" className="brand">Peblo TV</Link><Link to="/search">Search</Link></header>{children}</>}
function Home(){const q=useQuery({queryKey:['cat'],queryFn:()=>get('/catalog')});if(q.isLoading)return <div className="loading">Loading Peblo TV…</div>;if(q.isError)return <div className="empty">Catalogue unavailable.</div>;const sections=q.data.sections as any;const featured=sections.featured?.[0]||(Object.values(sections) as any[])[0]?.[0];return <main>{featured&&<section className="hero" style={{backgroundImage:`linear-gradient(90deg,#090b13 10%,transparent 80%),url(${img(featured.artwork.banner)})`}}><div><span className="eyebrow">FEATURED</span><h1>{featured.title}</h1><p>{featured.synopsis}</p><Link className="primary" to={`/show/${featured.slug}`}>Explore show</Link></div></section>}{Object.entries(sections).map(([sec,shows]:any)=><section className="row" key={sec}><h2>{sec}</h2><div className="cards">{shows.map((s:any)=><Link to={`/show/${s.slug}`} className="tile" key={s.slug}><div className="poster"><img src={img(s.artwork.poster)} loading="lazy"/><div className="shine"/></div><b>{s.title}</b></Link>)}</div></section>)}</main>}
function Search(){const [q,setQ]=React.useState('');const [cat,setCat]=React.useState('');const [lang,setLang]=React.useState('');const query=useQuery({queryKey:['search',q,cat,lang],queryFn:()=>get(`/catalog/search?q=${encodeURIComponent(q)}${cat?'&category='+cat:''}${lang?'&language='+lang:''}`),enabled:q.length>0||!!cat||!!lang});return <main className="search"><h1>Search</h1><div className="filters"><input autoFocus placeholder="Search shows, episodes or categories" value={q} onChange={e=>setQ(e.target.value)}/><select value={cat} onChange={e=>setCat(e.target.value)}><option value="">All categories</option><option>adventure</option><option>learning</option><option>music</option><option>science</option><option>stories</option><option>travel</option></select><select value={lang} onChange={e=>setLang(e.target.value)}><option value="">All languages</option><option value="en">English</option><option value="hi">Hindi</option></select></div>{query.isLoading?<p>Searching…</p>:query.data?.results?.length?<div className="cards">{query.data.results.map((s:any)=><Link to={`/show/${s.slug}`} className="tile" key={s.slug}><div className="poster"><img src={img(s.artwork.poster)}/></div><b>{s.title}</b></Link>)}</div>:<div className="empty"><h2>No results</h2><p>Try another title, category, or language.</p></div>}</main>}
function Show(){const {slug}=useParams();const q=useQuery({queryKey:['cat'],queryFn:()=>get('/catalog')});if(q.isLoading)return <div className="loading">Loading…</div>;const all=Object.values(q.data.sections).flat() as any[];const s=all.find(x=>x.slug===slug);if(!s)return <div className="empty">Show not found.</div>;return <main className="detail"><div className="detailhero" style={{backgroundImage:`linear-gradient(90deg,#090b13 15%,transparent),url(${img(s.artwork.banner)})`}}><div><h1>{s.title}</h1><p>{s.synopsis}</p><div className="tags">{s.categories.map((c:string)=><span key={c}>{c}</span>)}</div></div></div>{s.trailers?.length>0&&<section><h2>Trailer</h2>{s.trailers.map((t:any)=><div className="episode" key={t.content_group}><img src={img(t.artwork.thumbnail)} /><div><h3>{t.title}</h3><p>{t.languages.join(' · ')} · {t.duration_seconds}s</p></div></div>)}</section>}{s.seasons.map((season:any)=><section key={season.season_number}><h2>Season {season.season_number}</h2>{season.episodes.map((e:any)=><div className="episode" key={e.content_group}><img src={img(e.artwork.thumbnail)}/><div><h3>{e.episode_number}. {e.title}</h3><p>{e.duration_seconds}s · Languages: {e.languages.join(', ')}</p><small>{e.synopsis}</small></div></div>)}</section>)}</main>}
import * as React from 'react';
function App(){return <BrowserRouter><Layout><Routes><Route path="/" element={<Home/>}/><Route path="/search" element={<Search/>}/><Route path="/show/:slug" element={<Show/>}/></Routes></Layout></BrowserRouter>}
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={new QueryClient()}><App/></QueryClientProvider>);
